import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";
import inlineImportPlugin from "esbuild-plugin-inline-import";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const external = [
	"@codemirror/autocomplete",
	"@codemirror/closebrackets",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/comment",
	"@codemirror/fold",
	"@codemirror/gutter",
	"@codemirror/highlight",
	"@codemirror/history",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/matchbrackets",
	"@codemirror/panel",
	"@codemirror/rangeset",
	"@codemirror/rectangular-selection",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/stream-parser",
	"@codemirror/text",
	"@codemirror/tooltip",
	"@codemirror/view",
	"@lezer/highlight",
	...builtins
];

function createBuildArgs(format, outfile) {
	return {
		banner: {
			js: banner,
		},
		entryPoints: ["src/main.ts"],
		bundle: true,
		external,
		format,
		target: "es2016",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outfile,
		plugins: [
			inlineImportPlugin()
		]
	};
}

if (!prod) {
	const ctx = await esbuild.context(createBuildArgs("cjs", "main.js"));
	ctx.watch().catch(() => process.exit(1));
}
else {
	await esbuild.build(createBuildArgs("cjs", "main.js")).catch(() => process.exit(1));
	await esbuild.build(createBuildArgs("esm", "main.mjs")).catch(() => process.exit(1));
}
