import esbuild from "esbuild";
import process from "process";
import path from "path";
import { readFile } from "fs/promises";
import builtins from "builtin-modules";

const banner =
`/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

const prod = (process.argv[2] === "production");
const external = [
	"@codemirror/autocomplete",
	"@codemirror/closebrackets",
	"@codemirror/collab",
	"@codemirror/commands",
	"@codemirror/comment",
	"@codemirror/fold",
	"@codemirror/gutter",
	"@codemirror/highlight",
	"@codemirror/history",
	"@codemirror/language",
	"@codemirror/lint",
	"@codemirror/matchbrackets",
	"@codemirror/panel",
	"@codemirror/rangeset",
	"@codemirror/rectangular-selection",
	"@codemirror/search",
	"@codemirror/state",
	"@codemirror/stream-parser",
	"@codemirror/text",
	"@codemirror/tooltip",
	"@codemirror/view",
	"@lezer/highlight",
	...builtins
];

function toPosixPath(value) {
	return value.split(path.sep).join("/");
}

/**
 * The upstream inline-import plugin uses the absolute resolved file path as the
 * module id. esbuild then copies that path into generated bundle comments,
 * leaking local machine paths. This local replacement keeps the absolute path
 * in pluginData for file loading, but exposes only a repo-relative virtual path
 * to esbuild.
 */
function createInlineImportPlugin(options = {}) {
	const {
		filter = /^inline:/,
		namespace = "inline-import",
		transform = async (contents) => contents
	} = options;

	return {
		name: "inline-import-sanitized",
		setup(build) {
			build.onResolve({ filter }, (args) => {
				const requestPath = args.path.replace(filter, "");
				const absolutePath = path.resolve(args.resolveDir, requestPath);
				const relativePath = toPosixPath(path.relative(process.cwd(), absolutePath));

				return {
					path: `inline:${relativePath}`,
					namespace,
					pluginData: {
						absolutePath
					}
				};
			});

			build.onLoad({ filter: /.*/, namespace }, async (args) => {
				const absolutePath = args.pluginData?.absolutePath;
				if (typeof absolutePath !== "string") {
					throw new Error(`Missing absolute path for inline import '${args.path}'.`);
				}

				let contents = await readFile(absolutePath, "utf8");
				if (typeof transform === "function") {
					contents = await transform(contents, {
						...args,
						path: absolutePath
					});
				}

				return {
					contents,
					loader: "text"
				};
			});
		}
	};
}

function createBuildArgs(format, outfile) {
	return {
		banner: {
			js: banner,
		},
		entryPoints: ["src/main.ts"],
		bundle: true,
		external,
		format,
		target: "es2016",
		logLevel: "info",
		sourcemap: prod ? false : "inline",
		treeShaking: true,
		outfile,
		plugins: [
			createInlineImportPlugin()
		]
	};
}

if (!prod) {
	const ctx = await esbuild.context(createBuildArgs("cjs", "main.js"));
	ctx.watch().catch(() => process.exit(1));
}
else {
	await esbuild.build(createBuildArgs("cjs", "main.js")).catch(() => process.exit(1));
	await esbuild.build(createBuildArgs("esm", "main.mjs")).catch(() => process.exit(1));
}
